# Generated by Django 3.0.5 on 2022-05-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartParking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
